name: ssh-action-deploy

on:
  workflow_dispatch:

jobs:
  build:
    name: Ubuntu-ssh
    runs-on: ubuntu-20.04   
    steps:
      - name: Github actions...
        uses: actions/checkout@v3
      - name: Deploy with ssh...
        uses: sebastianjnuwu/ssh-action-deploy@v1
        with:
          IP: ${{ secrets.IP_SERVER }}
          USER: ${{ secrets.USER_SERVER }}
          KEY: ${{ secrets.SSH_PASS }}
          FOLDER: 'home/nikalex/test_deploy'
          RUN: 'ls -a; pwd'
