name: Java-test

on:
  push:
  workflow_dispatch:                                                   #Ручной запуск для тестирования
 
env:
  path: java_test_folder
  artifact_name: Package_test
  check_file_name: pom.xml

jobs:
  running_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3                                       #скачивается копия репозитория в среду выполнения
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
         java-version: '17'                                             #JDK version 17 Eclipse Adoptium
         distribution: 'adopt'         
         cache: maven                                                   #Кэширование зависимостей - локальный репозиторий Maven будет храниться в кэше
      - name: Build with Maven                                          #инструмент для автоматизации сборки проектов
        run: mvn --batch-mode --update-snapshots verify
        
      - run: mkdir java_test_folder && cp target/*.jar java_test_folder #Создание папки для хранения артефакта  
      - uses: actions/upload-artifact@v3
        with:
         name: ${{ env.artifact_name }}
         path: ${{ env.path }}
         
      - name: Checkout files                                            #проверка наличия файла pom.xml в проекте
        uses: Bhacaz/checkout-files@v2
        with:
          files: ${{ env.check_file_name }}
          
      - name: deploy file
        uses: ChenjxJames/SFTP-Deploy-Action@v1.3.2
        with:
          username: 'nikalex'
          server: '80.85.241.235'
          ssh_private_key: ${{ secrets.SSH_KEY }}
          local_path: '/home/runner/work/spring-petclinic/spring-petclinic/java_test_folder/*'
          remote_path: '/home/nikalex/deploy'
          args: '-o ConnectTimeout=5'
      
   
  download_artifact:                                                    #Выгружаем артефакт
   needs: running_build                                                 #Выполняем job, если предыдущий ОК
   runs-on: ubuntu-latest
   steps:
     - name: Download_build
       uses: actions/download-artifact@v3
       with:
        name: ${{ env.artifact_name }}


 
