name: Java-test

on: workflow_dispatch                 #Ручной запуск

jobs:
  running_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
         java-version: '17'           #JDK version 17 Adoptium
         distribution: 'adopt'         
         cache: maven                 #Кэширование зависимостей - локальный репозиторий Maven будет храниться в кэше
      - name: Build with Maven        #инструмент для автоматизации сборки проектов
        run: mvn --batch-mode --update-snapshots verify
        
      - run: mkdir java_test_folder && cp target/*.jar java_test_folder #Создание папки для хранения артефакта  
      - uses: actions/upload-artifact@v3
        with:
         name: Package_test
         path: java_test_folder
   
  download_artifact:                                                    #Выгружаем артефакт
   needs: running_build 
   runs-on: ubuntu-latest
   steps:
     - name: Download_build
       uses: actions/download-artifact@v3
       with:
        name: Package_test


 
